osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
    include:
        -
            os: osx
            osx_image: xcode12u
        -
            os: linux
            env: 'CC=clang CXX=clang++ npm_config_clang=1'
            compiler: clang
cache:
    directories:
        - node_modules
        - $HOME/.electron
        - $HOME/.cache
addons:
    apt:
        packages:
            - libgnome-keyring-dev
            - icnsutils
install:
    - 'nvm install 10'
    - 'curl -o- -L https://yarnpkg.com/install.sh | bash'
    - 'source ~/.bashrc'
    - 'npm install -g xvfb-maybe'
    - yarn
script:
    - 'yarn run dist'
#branches:
#    only:
#	- master
#	- feature/ci
